

# Custom Centered Message :D
bedwars-start-message:
  lines:
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&c&lBed&f&lWars"
    - "&f"
    - "&fProtect your bed and destroy the enemy beds"
    - "&fCollect Iron, Gold, Diamond and Emeralds"
    - "&fPurchase items and upgrades from dealers"
    - "Be the last team standing to win"
    - "&f"
    - "&f"
# Edit Spawn Values


# Wingman must be called
# name: "Wingman-Speed"
spawner-rates:
  -
    name: "Solos-Speed"
    playersPerTeam: 1
    spawn-rate: 0.75
  -
    name: "Duos-Speed"
    playersPerTeam: 1
    spawn-rate: 1
  -
    name: "Trios-Speed"
    playersPerTeam: 1
    spawn-rate: 1.25
  -
    name: "Quads-Speed"
    playersPerTeam: 1
    spawn-rate: 1.5
  -
    name: "Wingman-Speed"
    playersPerTeam: 2
    spawn-rate: 1.5





