

# Custom Centered Message :D
bedwars-start-message:
  lines:
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&f"
    - "&c&lBed&f&lWars"
    - "&f"
    - "&fProtect your bed and destroy the enemy beds"
    - "&fCollect Iron, Gold, Diamond and Emeralds"
    - "&fPurchase items and upgrades from dealers"
    - "Be the last team standing to win"
    - "&f"
    - "&f"
# Edit Spawn Values


# Wingman must be called
# name: "Wingman-Speed"
spawner-rates:
  Solos:
    name: "Solos-Speed"
    playersPerTeam: 1
    spawn-rate: 0.75
  Duos:
    name: "Duos-Speed"
    playersPerTeam: 1
    spawn-rate: 1
  Trios:
    name: "Trios-Speed"
    playersPerTeam: 1
    spawn-rate: 1.25
  Quads:
    name: "Quads-Speed"
    playersPerTeam: 1
    spawn-rate: 1.5
  Wingman:
    name: "Wingman-Speed"
    playersPerTeam: 2
    NoOfTeams: 2   # Optional
    spawn-rate: 1.5



arena:
  roundEnd:
    worldRemovalDelay: 600
    
    


