name: MBedwarsSpawnerRates
version: '${project.version}'
main: me.crypticzxi.mbedwars.spawnerrates.MBedwarsSpawnerRates
api-version: 1.17
api: MBedwarsSpawnerRates
authors: [ CrypticzXI ]
description: Just allows diffrent gamemodes to have diffrent spawn rates init
depend: [ MBedwars, SlimeWorldManager ]
commands:
  spawnerrates:
    description: Reload the plugin init
    usage: /spawnerrates
    permission: spawnerrates.admin